"""empty message

Revision ID: 0424572176b7
Revises: 38df01248df4
Create Date: 2019-10-16 23:46:33.484987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0424572176b7'
down_revision = '38df01248df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=150), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Abilities_Name'), 'Abilities', ['Name'], unique=False)
    op.add_column('charactersheet', sa.Column('ATD', sa.Integer(), nullable=True))
    op.add_column('charactersheet', sa.Column('ATN', sa.Integer(), nullable=True))
    op.add_column('charactersheet', sa.Column('AU', sa.Integer(), nullable=True))
    op.add_column('charactersheet', sa.Column('CH', sa.Integer(), nullable=True))
    op.add_column('charactersheet', sa.Column('GE', sa.Integer(), nullable=True))
    op.add_column('charactersheet', sa.Column('GG', sa.Integer(), nullable=True))
    op.add_column('charactersheet', sa.Column('IN', sa.Integer(), nullable=True))
    op.add_column('charactersheet', sa.Column('INI', sa.Integer(), nullable=True))
    op.add_column('charactersheet', sa.Column('KK', sa.Integer(), nullable=True))
    op.add_column('charactersheet', sa.Column('LE', sa.Integer(), nullable=True))
    op.add_column('charactersheet', sa.Column('MB', sa.Integer(), nullable=True))
    op.add_column('charactersheet', sa.Column('Name', sa.String(length=150), nullable=True))
    op.add_column('charactersheet', sa.Column('PA', sa.Integer(), nullable=True))
    op.add_column('charactersheet', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('charactersheet', sa.Column('job', sa.String(length=150), nullable=True))
    op.add_column('charactersheet', sa.Column('sex', sa.String(length=5), nullable=True))
    op.add_column('charactersheet', sa.Column('size', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_charactersheet_Name'), 'charactersheet', ['Name'], unique=False)
    op.create_index(op.f('ix_charactersheet_job'), 'charactersheet', ['job'], unique=False)
    op.create_index(op.f('ix_charactersheet_sex'), 'charactersheet', ['sex'], unique=False)
    op.create_index(op.f('ix_charactersheet_size'), 'charactersheet', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charactersheet_size'), table_name='charactersheet')
    op.drop_index(op.f('ix_charactersheet_sex'), table_name='charactersheet')
    op.drop_index(op.f('ix_charactersheet_job'), table_name='charactersheet')
    op.drop_index(op.f('ix_charactersheet_Name'), table_name='charactersheet')
    op.drop_column('charactersheet', 'size')
    op.drop_column('charactersheet', 'sex')
    op.drop_column('charactersheet', 'job')
    op.drop_column('charactersheet', 'age')
    op.drop_column('charactersheet', 'PA')
    op.drop_column('charactersheet', 'Name')
    op.drop_column('charactersheet', 'MB')
    op.drop_column('charactersheet', 'LE')
    op.drop_column('charactersheet', 'KK')
    op.drop_column('charactersheet', 'INI')
    op.drop_column('charactersheet', 'IN')
    op.drop_column('charactersheet', 'GG')
    op.drop_column('charactersheet', 'GE')
    op.drop_column('charactersheet', 'CH')
    op.drop_column('charactersheet', 'AU')
    op.drop_column('charactersheet', 'ATN')
    op.drop_column('charactersheet', 'ATD')
    op.drop_index(op.f('ix_Abilities_Name'), table_name='Abilities')
    op.drop_table('Abilities')
    # ### end Alembic commands ###
