"""empty message

Revision ID: 38df01248df4
Revises: 
Create Date: 2019-10-16 23:31:52.511376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38df01248df4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permissionname', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_action'), 'permission', ['action'], unique=True)
    op.create_index(op.f('ix_permission_permissionname'), 'permission', ['permissionname'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_rolename'), 'role', ['rolename'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('login_tries', sa.Integer(), nullable=True),
    sa.Column('account_suspended', sa.Boolean(), nullable=True),
    sa.Column('real_name', sa.String(length=200), nullable=True),
    sa.Column('image_name', sa.String(length=200), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('charactersheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('path', sa.String(length=254), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('subfolder', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('loadcount', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('entry_image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_name'), 'download', ['name'], unique=True)
    op.create_index(op.f('ix_download_path'), 'download', ['path'], unique=True)
    op.create_table('roletopermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('roletopermission_index', 'roletopermission', ['role_id', 'permission_id'], unique=True)
    op.create_table('usertorole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('usertorole_index', 'usertorole', ['user_id', 'role_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('usertorole_index', table_name='usertorole')
    op.drop_table('usertorole')
    op.drop_index('roletopermission_index', table_name='roletopermission')
    op.drop_table('roletopermission')
    op.drop_index(op.f('ix_download_path'), table_name='download')
    op.drop_index(op.f('ix_download_name'), table_name='download')
    op.drop_table('download')
    op.drop_table('charactersheet')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_rolename'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_permissionname'), table_name='permission')
    op.drop_index(op.f('ix_permission_action'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
