"""empty message

Revision ID: 4eece65df04a
Revises: 
Create Date: 2019-10-17 13:46:06.237566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eece65df04a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permissionname', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_action'), 'permission', ['action'], unique=True)
    op.create_index(op.f('ix_permission_permissionname'), 'permission', ['permissionname'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_rolename'), 'role', ['rolename'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('login_tries', sa.Integer(), nullable=True),
    sa.Column('account_suspended', sa.Boolean(), nullable=True),
    sa.Column('real_name', sa.String(length=200), nullable=True),
    sa.Column('image_name', sa.String(length=200), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('Charactersheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=150), nullable=True),
    sa.Column('sex', sa.String(length=5), nullable=True),
    sa.Column('job', sa.String(length=150), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('KK', sa.Integer(), nullable=True),
    sa.Column('AU', sa.Integer(), nullable=True),
    sa.Column('GE', sa.Integer(), nullable=True),
    sa.Column('IN', sa.Integer(), nullable=True),
    sa.Column('CH', sa.Integer(), nullable=True),
    sa.Column('MB', sa.Integer(), nullable=True),
    sa.Column('ATN', sa.Integer(), nullable=True),
    sa.Column('PA', sa.Integer(), nullable=True),
    sa.Column('ATD', sa.Integer(), nullable=True),
    sa.Column('INI', sa.Integer(), nullable=True),
    sa.Column('LE', sa.Integer(), nullable=True),
    sa.Column('GG', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Charactersheet_Name'), 'Charactersheet', ['Name'], unique=False)
    op.create_index(op.f('ix_Charactersheet_job'), 'Charactersheet', ['job'], unique=False)
    op.create_index(op.f('ix_Charactersheet_sex'), 'Charactersheet', ['sex'], unique=False)
    op.create_index(op.f('ix_Charactersheet_size'), 'Charactersheet', ['size'], unique=False)
    op.create_table('download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('path', sa.String(length=254), nullable=True),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('subfolder', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('loadcount', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('entry_image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_name'), 'download', ['name'], unique=True)
    op.create_index(op.f('ix_download_path'), 'download', ['path'], unique=True)
    op.create_table('roletopermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('roletopermission_index', 'roletopermission', ['role_id', 'permission_id'], unique=True)
    op.create_table('usertorole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('usertorole_index', 'usertorole', ['user_id', 'role_id'], unique=True)
    op.create_table('Abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(length=150), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['char'], ['Charactersheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Abilities_Name'), 'Abilities', ['Name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Abilities_Name'), table_name='Abilities')
    op.drop_table('Abilities')
    op.drop_index('usertorole_index', table_name='usertorole')
    op.drop_table('usertorole')
    op.drop_index('roletopermission_index', table_name='roletopermission')
    op.drop_table('roletopermission')
    op.drop_index(op.f('ix_download_path'), table_name='download')
    op.drop_index(op.f('ix_download_name'), table_name='download')
    op.drop_table('download')
    op.drop_index(op.f('ix_Charactersheet_size'), table_name='Charactersheet')
    op.drop_index(op.f('ix_Charactersheet_sex'), table_name='Charactersheet')
    op.drop_index(op.f('ix_Charactersheet_job'), table_name='Charactersheet')
    op.drop_index(op.f('ix_Charactersheet_Name'), table_name='Charactersheet')
    op.drop_table('Charactersheet')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_rolename'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_permissionname'), table_name='permission')
    op.drop_index(op.f('ix_permission_action'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
