"""empty message

Revision ID: e2e936420a03
Revises: 254f929f6ff2
Create Date: 2019-10-18 21:43:45.849219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2e936420a03'
down_revision = '254f929f6ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Abilites_cat', sa.Column('Abilities', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Abilites_cat', 'Abilities', ['Abilities'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Abilites_cat', type_='foreignkey')
    op.drop_column('Abilites_cat', 'Abilities')
    # ### end Alembic commands ###
