"""empty message

Revision ID: f4cf3d89d7aa
Revises: 0424572176b7
Create Date: 2019-10-16 23:48:11.583137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cf3d89d7aa'
down_revision = '0424572176b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Collection')
    # ### end Alembic commands ###
